package View.View;


import View.View.Home.Home;
import Utils.Observer.interfaces.IObserver;
import View.View.Music.MusicContainer;
import View.View.Playlist.PlaylistPanel;
import View.View.Playlist.PlaylistContainer;
import javax.swing.JOptionPane;
import Utils.JPanelManager;
import Model.Playlist;
import Model.interfaces.IPlaylist;
import View.View.Records.SignIn;
import View.View.User.UserContainer;


/**
 *
 * @author mateus
 */
public class Main extends javax.swing.JFrame implements IObserver {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();     
        new JPanelManager(container, new Home());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPainel = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        jButtonPlaylists2 = new javax.swing.JLabel();
        LateralBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPlaylists = new javax.swing.JLabel();
        jButtonHome1 = new javax.swing.JLabel();
        jButtonMusics1 = new javax.swing.JLabel();
        jButtonProfile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(619, 400));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPainel.setPreferredSize(new java.awt.Dimension(600, 400));
        mainPainel.setLayout(new java.awt.BorderLayout());

        container.setPreferredSize(new java.awt.Dimension(600, 400));
        container.setLayout(new java.awt.BorderLayout());

        jButtonPlaylists2.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonPlaylists2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPlaylists2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonPlaylists2.setText("Playlists");
        jButtonPlaylists2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonPlaylists2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlaylists2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPlaylists2MouseClicked(evt);
            }
        });
        container.add(jButtonPlaylists2, java.awt.BorderLayout.CENTER);

        mainPainel.add(container, java.awt.BorderLayout.CENTER);

        LateralBar.setBackground(new java.awt.Color(52, 52, 52));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USERNAME");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Logout");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jButtonPlaylists.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonPlaylists.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPlaylists.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonPlaylists.setText("Playlists");
        jButtonPlaylists.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonPlaylists.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlaylists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPlaylistsMouseClicked(evt);
            }
        });

        jButtonHome1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonHome1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonHome1.setText("Home");
        jButtonHome1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonHome1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHome1MouseClicked(evt);
            }
        });

        jButtonMusics1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonMusics1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMusics1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonMusics1.setText("Musics");
        jButtonMusics1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonMusics1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMusics1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMusics1MouseClicked(evt);
            }
        });

        jButtonProfile.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonProfile.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonProfile.setText("Profile");
        jButtonProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonProfileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LateralBarLayout = new javax.swing.GroupLayout(LateralBar);
        LateralBar.setLayout(LateralBarLayout);
        LateralBarLayout.setHorizontalGroup(
            LateralBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LateralBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LateralBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LateralBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonHome1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPlaylists, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMusics1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addComponent(jButtonProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        LateralBarLayout.setVerticalGroup(
            LateralBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LateralBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButtonHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMusics1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPainel.add(LateralBar, java.awt.BorderLayout.LINE_START);

        getContentPane().add(mainPainel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int option = JOptionPane.showConfirmDialog(null, "Sure you want to leave?", "JPlayer", JOptionPane.OK_OPTION);
        
        if(option == 0){
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButtonHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHome1MouseClicked
       new JPanelManager(container, new Home());
    }//GEN-LAST:event_jButtonHome1MouseClicked

    private void jButtonMusics1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMusics1MouseClicked
         new JPanelManager(container, new MusicContainer());
    }//GEN-LAST:event_jButtonMusics1MouseClicked

    private void jButtonPlaylistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlaylistsMouseClicked
        
        PlaylistContainer playlists = new PlaylistContainer();
        playlists.addObserver(this);
        new JPanelManager(container, playlists);
    }//GEN-LAST:event_jButtonPlaylistsMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       
        int option = JOptionPane.showConfirmDialog(null, "Sure you want logout?", "JPlayer", JOptionPane.OK_OPTION);
        
        if(option == 0){
           new SignIn().setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
      
        System.out.println(this.getWidth());
    }//GEN-LAST:event_formComponentResized

    private void jButtonPlaylists2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlaylists2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlaylists2MouseClicked

    private void jButtonProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProfileMouseClicked

          new JPanelManager(container, new UserContainer());
    }//GEN-LAST:event_jButtonProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LateralBar;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jButtonHome1;
    private javax.swing.JLabel jButtonMusics1;
    private javax.swing.JLabel jButtonPlaylists;
    private javax.swing.JLabel jButtonPlaylists2;
    private javax.swing.JLabel jButtonProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPainel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Object publisher) {

        if( publisher instanceof IPlaylist){
            Playlist playlist = (Playlist) publisher;
            new JPanelManager(container, new PlaylistPanel(playlist));
        }
    }
}
