/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.View.User;

import Facades.UserFacade;
import Model.interfaces.IUser;
import TableModel.SelectMusicTableModel;
import TableModel.SelectUserTableModel;
import TableModel.UserTableModel;
import Utils.Observer.interfaces.IObserver;
import View.View.Editions.User.EditUser;
import View.View.Main;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class UserContainer extends javax.swing.JPanel implements IObserver {

    /**
     * Creates new form UserContainer
     */
    
    private UserTableModel model = new UserTableModel();
    private SelectUserTableModel removeModel = new SelectUserTableModel();
    private final UserFacade facade = new UserFacade();
    
    public UserContainer() {
        initComponents();
        listAllUsersInDatabase();   
        jLabelConfirmDelete.setVisible(false); 
    }
    
    private void listAllUsersInDatabase(){
        
        model.insertWithRemove(facade.GetAllUsers());
        jTableMusics1.setModel(model);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMusics = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelConfirmDelete = new javax.swing.JLabel();
        jLabelDeleteUser = new javax.swing.JLabel();
        jLabelEditUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldSearchBar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMusics1 = new javax.swing.JTable();

        jTableMusics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMusics);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Songs");

        jPanel2.setBackground(new java.awt.Color(34, 34, 34));

        jLabelConfirmDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelConfirmDelete.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConfirmDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConfirmDelete.setText("Confirm");
        jLabelConfirmDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelConfirmDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConfirmDelete.setEnabled(false);
        jLabelConfirmDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelConfirmDeleteMouseClicked(evt);
            }
        });

        jLabelDeleteUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDeleteUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDeleteUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDeleteUser.setText("Delete");
        jLabelDeleteUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelDeleteUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDeleteUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDeleteUserMouseClicked(evt);
            }
        });

        jLabelEditUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEditUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditUser.setText("Edit");
        jLabelEditUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelEditUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEditUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConfirmDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelConfirmDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));

        jTextFieldSearchBar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldSearchBarCaretUpdate(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSearchBar))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Users");

        jTableMusics1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableMusics1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelConfirmDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelConfirmDeleteMouseClicked
                    int option = JOptionPane.showConfirmDialog(null, "Sure you want to Remove users ?", "JPlayer", JOptionPane.OK_OPTION);
        
        if(option == 0){
           
            List<IUser> selecteds = removeModel.GetAllSelected();
            if(selecteds.isEmpty()){
                JOptionPane.showMessageDialog(null, "Select at least one user.");
                return;
            }
          
            List<IUser> currentIUsers = model.getData();
            
         
            selecteds.forEach( users -> {
                currentIUsers.removeIf( user -> user.getId() == users.getId());
            });
            
            model.insertUser(currentIUsers);
          
            boolean result = facade.removeUsersDb(selecteds);
            if(!result){
                JOptionPane.showMessageDialog(null, "An error occurred while trying to delete the selected songs. Try again");         
            }else{
                removeModel.removeUser(selecteds); //remove visually
            }
            
        }
        jLabelConfirmDelete.setEnabled(false);
        jTableMusics1.setModel(model);
              
        
    }//GEN-LAST:event_jLabelConfirmDeleteMouseClicked

    private void jLabelDeleteUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeleteUserMouseClicked

        if(!jLabelConfirmDelete.isEnabled()){
           removeModel.insertUser(model.getData());
           jTableMusics1.setModel(removeModel);
           jLabelConfirmDelete.setEnabled(true); 
           jLabelConfirmDelete.setVisible(true);
        }else{
            jTableMusics1.setModel(model);
            jLabelConfirmDelete.setEnabled(false); 
           jLabelConfirmDelete.setVisible(false);
        }
        
    }//GEN-LAST:event_jLabelDeleteUserMouseClicked

    private void jLabelEditUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditUserMouseClicked
        int selectedRow = jTableMusics1.getSelectedRow();
        
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(null, "Select at least one music in table.");
            return;
        }
        
        IUser selectedUser = model.getData(selectedRow);
        EditUser modalEdit = new EditUser(selectedUser);
        modalEdit.addObserver(this);
        modalEdit.setVisible(true);

    }//GEN-LAST:event_jLabelEditUserMouseClicked

    private void jTextFieldSearchBarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldSearchBarCaretUpdate
        model.SearchUserByName(jTextFieldSearchBar.getText());
        jTableMusics1.setModel(model);
    }//GEN-LAST:event_jTextFieldSearchBarCaretUpdate

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelConfirmDelete;
    private javax.swing.JLabel jLabelDeleteUser;
    private javax.swing.JLabel jLabelEditUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMusics;
    private javax.swing.JTable jTableMusics1;
    private javax.swing.JTextField jTextFieldSearchBar;
    // End of variables declaration//GEN-END:variables
 
    @Override
    public void update(Object publisher) {
        
        if(publisher instanceof Boolean){
            
            if( (( Boolean) publisher)){
                listAllUsersInDatabase();    
            }
        }

    }


}
